BEGIN;

DROP TABLE IF EXISTS trip_requests;
DROP TABLE IF EXISTS route_stops;
DROP TABLE IF EXISTS buses;
DROP TABLE IF EXISTS stops;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS route_direction;
DROP TYPE IF EXISTS bus_tracking_status;
DROP TYPE IF EXISTS user_role;

DROP EXTENSION IF EXISTS postgis;
DROP EXTENSION IF EXISTS pgcrypto;
DROP EXTENSION IF EXISTS citext;

COMMIT;
